name: "z Slack Notify"

on:
  workflow_dispatch:

jobs:
  notify:
    name: Slack Notify
    runs-on: ubuntu-latest

    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          errors: true

          payload: |
            channel: "${{ secrets.SLACK_CHANNEL_ID }}"
            text: "GitHub Actions notification test: ${{ job.status }}"

            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "Message Header"
                  emoji: true

              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    Hello world :ghost:

                    *GitHub Action build result:* `${{ job.status }}`

                    <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Actionsの実行結果を開く>
